parameters:
#    sm_login.example.class: SM\LoginBundle\Example

services:
#    sm_login.example:
#        class: %sm_login.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
